# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79bc78e96c150da68689a6a8748844bb60f200bf3acbe290b4b0bf0f9f25bcd1ca05a00e5ba92e2012b8e5335d35cb914450ba95e4dc95303dc7a387b58fa8d5

test:
  secret_key_base: 1b64e091478fc792cee62b0509c5104e2d7eb5d809d77b24a409f0adc3866638e2bdc6bca86b9a2ee1da68f56abe19686f3f50e4f4a22f252352314e3620b2e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
